Add madrid G13 device
128technology/interfacemaps pull request #18
Opened 2022-09-14 17:48 UTC by haberkornsam

explicitly define G13 device

2022-09-14 17:50 UTC, BenMatase requested changes

2022-09-14 17:55 UTC, BenMatase approved these changes

2022-09-14 19:20 UTC, BenMatase requested changes
Wait for confirmation from a physical device that it is actually the same as G53

2022-09-19 13:31 UTC, BenMatase approved these changes

2022-09-19 13:31 UTC, BenMatase commented on devicemaps.json
> +        "description": "Madrid - 8 ethernet, 1 lte",
Can you add a little note here like `only difference to the G53 is the last two pci port numbers are switched` something like that

2022-09-19 14:46 UTC, BenMatase approved these changes

2022-09-19 18:25 UTC, agrawalkaushik approved these changes

2022-09-19 18:25 UTC, merged