Update devicemaps.json to include LTE section for Silicom Madrid 90500-0151-G12 model
128technology/interfacemaps pull request #27
Opened 2023-05-24 17:52 UTC by avijitvjuniper

Including LTE section for Silicom Madrid 90500-0151-G12 model. Jira for tracking: https://128technology.atlassian.net/browse/WAN-1959

2023-05-25 00:58 UTC, BenMatase requested changes

2023-05-25 00:58 UTC, BenMatase commented on devicemaps.json
> +          "sku": "90500-0151-G12"
The vendor and sku here is supposed to reference another entry to inherit from. If you make this G11, you won't need to add the lte part.

2023-06-05 15:45 UTC, BenMatase approved these changes

2023-06-05 16:44 UTC, haberkornsam approved these changes

2023-06-05 17:50 UTC, merged